//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DROP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atcase
    {
        public int atcase_id { get; set; }
        public int at_id { get; set; }
        public string cases { get; set; }
    }
}
