//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DROP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class outcome
    {
        public int out_id { get; set; }
        public int pid { get; set; }
        public int acc_id { get; set; }
        public string filename { get; set; }
        public System.DateTime cdate { get; set; }
    
        public virtual process process { get; set; }
        public virtual user user { get; set; }
    }
}
