//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DROP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class process
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public process()
        {
            this.outcomes = new HashSet<outcome>();
        }
    
        public int pid { get; set; }
        public int quarter { get; set; }
        public int year { get; set; }
        public int copiatt_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<outcome> outcomes { get; set; }
        public virtual copiatt copiatt { get; set; }
    }
}
